/**
 * Makes every logo file from assets/brand/sitepilot-mark.svg: the favicons,
 * the desktop app icons, the Slack icon and the MCP server's icon. Run it
 * after changing the mark, from the repository root:
 * npm run generate:brand-assets
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { chromium } from "playwright";

const root = process.cwd();
const mark = readFileSync(
  join(root, "assets/brand/sitepilot-mark.svg"),
  "utf8"
);
// Full-bleed square, for Slack and iOS, which round the corners themselves.
const square = mark.replace(' rx="14"', "");
// macOS icons sit inside the 1024 canvas with a 100px margin.
const macos = mark.replace(
  'viewBox="0 0 64 64"',
  'viewBox="-7.77 -7.77 79.54 79.54"'
);

/** An ICO of PNG images, which every browser reads. */
function ico(images: Buffer[], sizes: number[]): Buffer {
  const header = Buffer.alloc(6 + 16 * images.length);
  header.writeUInt16LE(1, 2);
  header.writeUInt16LE(images.length, 4);
  let offset = header.length;
  images.forEach((data, index) => {
    const entry = 6 + 16 * index;
    const size = sizes[index] as number;
    header.writeUInt8(size >= 256 ? 0 : size, entry);
    header.writeUInt8(size >= 256 ? 0 : size, entry + 1);
    header.writeUInt16LE(1, entry + 4);
    header.writeUInt16LE(32, entry + 6);
    header.writeUInt32LE(data.length, entry + 8);
    header.writeUInt32LE(offset, entry + 12);
    offset += data.length;
  });
  return Buffer.concat([header, ...images]);
}

/** An ICNS of PNG images, keyed by Apple's type codes. */
function icns(entries: [string, Buffer][]): Buffer {
  const chunk = (type: string, data: Buffer): Buffer => {
    const head = Buffer.alloc(8);
    head.write(type, 0, "ascii");
    head.writeUInt32BE(data.length + 8, 4);
    return Buffer.concat([head, data]);
  };
  return chunk(
    "icns",
    Buffer.concat(entries.map(([type, data]) => chunk(type, data)))
  );
}

function write(path: string, data: Buffer | string): void {
  const file = join(root, path);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, data);
  console.log(`Wrote ${path}`);
}

async function main(): Promise<void> {
  const browser = await chromium.launch();
  const page = await browser.newPage();

  const png = async (svg: string, size: number): Promise<Buffer> => {
    await page.setViewportSize({ width: size, height: size });
    await page.setContent(
      `<style>html,body{margin:0;background:transparent}svg{display:block;width:${size}px;height:${size}px}</style>${svg}`
    );
    return page.screenshot({
      omitBackground: true,
      clip: { x: 0, y: 0, width: size, height: size }
    });
  };

  const favicons = [16, 32, 48];
  write(
    "apps/desktop/public/favicon.ico",
    ico(await Promise.all(favicons.map((size) => png(mark, size))), favicons)
  );
  copyFileSync(
    join(root, "assets/brand/sitepilot-mark.svg"),
    join(root, "apps/desktop/public/sitepilot-mark.svg")
  );
  console.log("Wrote apps/desktop/public/sitepilot-mark.svg");
  write("apps/desktop/public/apple-touch-icon.png", await png(square, 180));

  // electron-builder reads build/icon.icns for macOS and builds Windows and
  // Linux icons from build/icon.png. The PNG with a margin is the dev Dock icon.
  const mac = async (size: number) => png(macos, size);
  write(
    "apps/desktop/build/icon.icns",
    icns([
      ["icp4", await mac(16)],
      ["icp5", await mac(32)],
      ["ic11", await mac(32)],
      ["ic12", await mac(64)],
      ["ic07", await mac(128)],
      ["ic13", await mac(256)],
      ["ic08", await mac(256)],
      ["ic14", await mac(512)],
      ["ic09", await mac(512)],
      ["ic10", await mac(1024)]
    ])
  );
  write("apps/desktop/build/icon-macos.png", await mac(512));
  write("apps/desktop/build/icon.png", await png(mark, 1024));

  write("assets/brand/sitepilot-icon-512.png", await png(mark, 512));
  write("assets/brand/slack-app-icon.png", await png(square, 1024));

  const mcpIcon = (await png(mark, 128)).toString("base64");
  write(
    "packages/mcp-server/src/brand-icon.ts",
    `// Generated by scripts/generate-brand-assets.ts from assets/brand/sitepilot-mark.svg.\n` +
      `export const SITEPILOT_ICON_PNG = "data:image/png;base64,${mcpIcon}";\n`
  );

  await browser.close();
}

void main();
